version: "3.8"
name: openmldb_cluster

volumes:
  tablet1-data:
  tablet2-data:
  tablet3-data:
  lib-data:

services:
  openmldb-api:
    build: .
    restart: on-failure
    command:
      - "--role=apiserver"
      - "--endpoint=openmldb-api:9527"
      - "--zk_cluster=openmldb-zk:2181"
      - "--zk_root_path=/openmldb"
    ports:
      - 9527
    depends_on:
      - openmldb-ns1
      - openmldb-ns2

  openmldb-zk:
    image: zookeeper:3.4.14
    ports:
      - 2181

  openmldb-ns1:
    build: .
    command:
      - "--role=nameserver"
      - "--endpoint=openmldb-ns1:9527"
      - "--zk_cluster=openmldb-zk:2181"
      - "--zk_root_path=/openmldb"
    restart: on-failure
    depends_on:
      - openmldb-tablet1
      - openmldb-tablet2
      - openmldb-tablet3

  openmldb-ns2:
    build: .
    command:
      - "--role=nameserver"
      - "--endpoint=openmldb-ns2:9527"
      - "--zk_cluster=openmldb-zk:2181"
      - "--zk_root_path=/openmldb"
    restart: on-failure
    depends_on:
      - openmldb-tablet1
      - openmldb-tablet2
      - openmldb-tablet3

  openmldb-tablet1:
    build: .
    volumes:
      - tablet1-data:/var/lib/openmldb
      - lib-data:/opt/openmldb/udf
    command:
      - "--role=tablet"
      - "--endpoint=openmldb-tablet1:9527"
      - "--zk_cluster=openmldb-zk:2181"
      - "--zk_root_path=/openmldb"
    depends_on:
      - openmldb-zk
      - openmldb-tablet2

  openmldb-tablet2:
    build: .
    volumes:
      - tablet2-data:/var/lib/openmldb
      - lib-data:/opt/openmldb/udf
    command:
      - "--role=tablet"
      - "--endpoint=openmldb-tablet2:9527"
      - "--zk_cluster=openmldb-zk:2181"
      - "--zk_root_path=/openmldb"
    depends_on:
      - openmldb-zk
      - openmldb-tablet3

  openmldb-tablet3:
    build: .
    volumes:
      - tablet3-data:/var/lib/openmldb
      - lib-data:/opt/openmldb/udf
    command:
      - "--role=tablet"
      - "--endpoint=openmldb-tablet3:9527"
      - "--zk_cluster=openmldb-zk:2181"
      - "--zk_root_path=/openmldb"
    depends_on:
      - openmldb-zk
